### ISSUE TITLE
Invalid plugin code with flake8 v5

### ISSUE THREAD

**Issue by wwuck** [d1618033/flake8-if-statements#1]
* Operating System: Linux
* Python version: 3.10.6
* flake8-if-statements version used: 0.1.0

### Description

Run `flake8-if-statements` with `flake8>5`.  The plugin code is now restricted to maximum three letters and three numbers.

Reference: https://github.com/pycqa/flake8/issues/325

### What I Did

```bash
$ flake8
There was a critical error during execution of Flake8:
plugin code for `flake8-if-statements[IFSTMT]` does not match ^[A-Z]{1,3}[0-9]{0,3}$
```

**Comment by d1618033** [comment]
Thank you for the detailed issue @wwuck !
